In [17]:
from pprint import pprint
from IPython.display import display,HTML,IFrame
import modules.browser as browser

import numpy as np

import modules.plots as plots
import modules.rotation as rotation
import modules.affine as affine


# 検証用データの作成

In [18]:
client_right = np.array(
    [
        [0.6260809, -0.7287946, 0.27727395, 0.0],
        [0.5277127, 0.65780145, 0.53741616, 0.0],
        [-0.5740574, -0.19014505, 0.79643136, 0.0],
        [-0.3852316, 1.3070072, -0.24187692, 0.9999999],
    ]
)

client_both_right = np.array(
    [
        [0.06430586, -0.6509886, 0.7563589, 0.0],
        [0.6940623, 0.57376546, 0.43482298, 0.0],
        [-0.71703726, 0.49699852, 0.48872307, 0.0],
        [-0.13179393, 1.1662917, -0.42948368, 0.9999998],
    ]
)

client_both_left = np.array(
    [
        [-0.43660122, 0.88827, 0.14267299, 0.0],
        [-0.6418425, -0.19641805, -0.74125427, 0.0],
        [-0.63041043, -0.41520622, 0.6558859, 0.0],
        [-0.45987153, 1.1884942, -0.0532205, 0.9999998],
    ]
)

client_matrix = np.array(
    [
        client_right.T,
        client_both_left.T,
        client_both_right.T,
    ]
)

# print("client_matrix")
# print(client_matrix)

host_right = np.array(
    [
        [0.092240095, -0.5007555, 0.86065996, 0.0],
        [0.30278015, 0.8375217, 0.45484287, 0.0],
        [-0.94858617, 0.21863598, 0.22887182, 0.0],
        [-0.091274284, 1.3827536, -0.60816413, 0.9999996],
    ]
)

host_both_right = np.array(
    [
        [0.1284489, 0.43118837, 0.8930717, 0.0],
        [0.3820718, 0.80950046, -0.4457915, 0.0],
        [-0.9151621, 0.39847913, -0.060765553, 0.0],
        [0.13363218, 1.238118, -0.7244158, 0.99999964],
    ]
)

host_both_left = np.array(
    [
        [-0.5007684, 0.116484866, -0.8577073, 0.0],
        [0.3800316, -0.8607031, -0.33877146, 0.0],
        [-0.7776932, -0.49560198, 0.38674507, 0.0],
        [-0.45513877, 1.1767162, -0.5885545, 0.9999995],
    ]
)

host_matrix = np.array([host_right.T, host_both_right.T, host_both_left.T])
client_matrix = np.array([client_right.T, client_both_left.T, client_both_right.T])

host_matrix = np.array([client_right.T, client_both_left.T, client_both_right.T])
client_matrix = np.array([host_right.T, host_both_right.T, host_both_left.T])

host_matrix = np.array(
    [
        [
            [
                0.5562306642532349,
                0.5555832386016846,
                -0.618008553981781,
                -0.24337060749530792,
            ],
            [
                -0.6506398320198059,
                0.7537873983383179,
                0.09204696118831635,
                0.7893363237380981,
            ],
            [
                0.5169867277145386,
                0.35090163350105286,
                0.780764102935791,
                -0.5038592219352722,
            ],
            [0.0, 0.0, 0.0, 1.0000001192092896],
        ],
        [
            [
                0.1541898101568222,
                0.5248171091079712,
                -0.8371332287788391,
                -0.06998009979724884,
            ],
            [
                -0.6118054986000061,
                0.7160078883171082,
                0.33619382977485657,
                0.6919271349906921,
            ],
            [
                0.7758345007896423,
                0.4603252410888672,
                0.43148720264434814,
                -0.5652991533279419,
            ],
            [0.0, 0.0, 0.0, 0.9999996423721313],
        ],
        [
            [
                -0.4974305033683777,
                -0.31042829155921936,
                -0.8100600242614746,
                -0.39988118410110474,
            ],
            [
                0.7428818345069885,
                -0.6346402764320374,
                -0.2129741758108139,
                0.7015295624732971,
            ],
            [
                -0.4479835033416748,
                -0.7077187299728394,
                0.5463011860847473,
                -0.3203715980052948,
            ],
            [0.0, 0.0, 0.0, 0.9999997615814209],
        ],
    ]
)
client_matrix = np.array(
    [
        [
            [
                0.8661612868309021,
                0.361994206905365,
                -0.34456488490104675,
                -0.416620671749115,
            ],
            [
                -0.3561864495277405,
                0.930767834186554,
                0.08247461915016174,
                0.9175246953964233,
            ],
            [
                0.3505653142929077,
                0.05129300057888031,
                0.9351325035095215,
                -0.3071862459182739,
            ],
            [0.0, 0.0, 0.0, 0.9999997615814209],
        ],
        [
            [
                0.6101363897323608,
                0.47927841544151306,
                -0.6308925747871399,
                -0.27676621079444885,
            ],
            [
                -0.39316582679748535,
                0.8744770884513855,
                0.28409498929977417,
                0.8279070854187012,
            ],
            [
                0.6878619194030762,
                0.07470865547657013,
                0.7219863533973694,
                -0.5423091053962708,
            ],
            [0.0, 0.0, 0.0, 0.9999997615814209],
        ],
        [
            [
                -0.785858154296875,
                -0.19526691734790802,
                -0.586769163608551,
                -0.5836778879165649,
            ],
            [
                0.5389275550842285,
                -0.6815949082374573,
                -0.49496009945869446,
                0.8163708448410034,
            ],
            [
                -0.30328965187072754,
                -0.7051944136619568,
                0.6408713459968567,
                -0.20289365947246552,
            ],
            [0.0, 0.0, 0.0, 0.9999998807907104],
        ],
    ]
)


print(host_matrix[0][:3, 3])
print(client_matrix[0][:3, 3])


[-0.24337061  0.78933632 -0.50385922]
[-0.41662067  0.9175247  -0.30718625]


# アフィン行列の作成からスケーリングの除去まで

In [19]:
host_to_client_affine_matrix = affine.generateAffineMatrix3DSelfLU(
    host_matrix, client_matrix
)
print("初期のアフィン行列の生成")
print("host_to_client_affine_matrix")
print(host_to_client_affine_matrix)


初期のアフィン行列の生成
host_to_client_affine_matrix
[[ 3.41439424e+00  2.59575502e+00  3.24412309e+00  1.40073682e-07]
 [-7.05418311e-01  3.00797267e-01 -1.00904486e+00 -1.53006233e-07]
 [ 5.90371654e+00  7.21116925e+00  9.05497628e+00  3.16783120e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [20]:
_, host_to_client_affine_matrix_rotation = affine.decompose_affine_matrix(
    host_to_client_affine_matrix
)
host_to_client_affine_matrix[:3, :3] = host_to_client_affine_matrix_rotation


client_right_position = client_matrix[0][:3, 3]
print("client_right_position")
print(client_right_position)

w
[[-0.37633006  0.75996359 -0.52993493]
 [ 0.06198685 -0.55004929 -0.83282856]
 [-0.92440971 -0.34626742  0.15989233]]
s
[14.04917478  1.17043129  0.79046661]
vh
[[-0.48302615 -0.54268597 -0.68715186]
 [ 0.80189712 -0.58932718 -0.09825729]
 [-0.35163441 -0.59848594  0.71983875]]
R
[[ 0.97753322  0.07352045 -0.19754377]
 [-0.17817303  0.78895578 -0.58805029]
 [ 0.11261957  0.61003567  0.78432985]]
R
[[ 0.97753322  0.07352045 -0.19754377]
 [-0.17817303  0.78895578 -0.58805029]
 [ 0.11261957  0.61003567  0.78432985]]
scale
[6.85635268 7.67003162 9.6713547 ]
client_right_position
[-0.41662067  0.9175247  -0.30718625]


In [21]:
url = browser.matrix_to_url(
np.array(
        [
            client_matrix[0].T,
            (host_to_client_affine_matrix @ host_matrix[0]).T,
            # client_matrix[1].T,
            # (host_to_client_affine_matrix @ host_matrix[1]).T,
            # client_matrix[2].T,
            # (host_to_client_affine_matrix @ host_matrix[2]).T,
        ]
    )
)
IFrame(src=url, width=1000, height=600)

In [22]:
url = browser.matrix_to_url(
np.array(
        [
            host_matrix[0].T,
            (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[0]).T,
            # host_matrix[1].T,
            # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[1]).T,
            # host_matrix[2].T,
            # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[2]).T,
        ]
    )
)
IFrame(src=url, width=1000, height=600)

In [31]:
url1 = browser.matrix_to_url(
np.array(
        [
            client_matrix[0].T,
            (host_to_client_affine_matrix @ host_matrix[0]).T,
            # client_matrix[1].T,
            # (host_to_client_affine_matrix @ host_matrix[1]).T,
            # client_matrix[2].T,
            # (host_to_client_affine_matrix @ host_matrix[2]).T,
        ]
    )
)

url2 = browser.matrix_to_url(
np.array(
        [
            host_matrix[0].T,
            (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[0]).T,
            # host_matrix[1].T,
            # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[1]).T,
            # host_matrix[2].T,
            # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[2]).T,
        ]
    )
)

# iframe1 = IFrame(src=url1, width=600, height=400)
# iframe2 = IFrame(src=url2, width=600, height=400)

iframe1 = IFrame(src=url1, width=600, height=400)
iframe2 = IFrame(src=url2, width=600, height=400)

display(HTML(f"""
<div style="display: flex; gap: 10px;">
    <div>
        <h2>host to client</h2>
        <div>{iframe1._repr_html_()}</div>
    </div>
    <div>
        <h2>client to host（逆行列）</h2>
        <div>{iframe2._repr_html_()}</div>
    </div>
</div>
"""))

# 回転成分の補正

In [24]:
ex_host_matrix = host_to_client_affine_matrix @ client_matrix[0]

host_to_client_affine_matrix = rotation.rotation(
    client_matrix[0],
    ex_host_matrix,
    host_to_client_affine_matrix,
)

print("host_to_client_affine_matrix")
print(host_to_client_affine_matrix)

url = browser.matrix_to_url(
    np.array(
        [
            client_matrix[0].T,
            (host_to_client_affine_matrix @ host_matrix[0]).T,
            # client_matrix[1].T,
            # (host_to_client_affine_matrix @ host_matrix[1]).T,
            # client_matrix[2].T,
            # (host_to_client_affine_matrix @ host_matrix[2]).T,
        ]
    )
)

url = browser.matrix_to_url(
np.array(
        [
            # host_matrix[0].T,
            # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[0]).T,
            # host_matrix[1].T,
            # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[1]).T,
            host_matrix[2].T,
            (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[2]).T,
        ]
    )
)
IFrame(src=url, width=1000, height=600)


host_to_client_affine_matrix
[[ 9.30915010e-01  3.04987220e-01  2.00947852e-01  1.40073682e-07]
 [-1.28286130e-01  7.88170145e-01 -6.01938944e-01 -1.53006233e-07]
 [-3.41964782e-01  5.34575176e-01  7.72845049e-01  3.16783120e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [25]:
ex_host_matrix = host_to_client_affine_matrix @ client_matrix[0]

host_to_client_affine_matrix = rotation.rotation(
    client_matrix[0],
    ex_host_matrix,
    host_to_client_affine_matrix,
)

print("host_to_client_affine_matrix")
print(host_to_client_affine_matrix)

url = browser.matrix_to_url(
    np.array(
        [
            client_matrix[0].T,
            (host_to_client_affine_matrix @ host_matrix[0]).T,
            # client_matrix[1].T,
            # (host_to_client_affine_matrix @ host_matrix[1]).T,
            # client_matrix[2].T,
            # (host_to_client_affine_matrix @ host_matrix[2]).T,
        ]
    )
)

# url = browser.matrix_to_url(
# np.array(
#         [
#             # host_matrix[0].T,
#             # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[0]).T,
#             host_matrix[1].T,
#             (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[1]).T,
#             # host_matrix[2].T,
#             # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[2]).T,
#         ]
#     )
# )

IFrame(src=url, width=1000, height=600)


host_to_client_affine_matrix
[[ 8.07303134e-01  2.28031909e-01  5.44300559e-01  1.40073682e-07]
 [-5.67475505e-02  9.48051736e-01 -3.13013773e-01 -1.53006233e-07]
 [-5.87402218e-01  2.21809276e-01  7.78305390e-01  3.16783120e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [26]:
ex_host_matrix = host_to_client_affine_matrix @ client_matrix[0]

host_to_client_affine_matrix = rotation.rotation(
    client_matrix[0],
    ex_host_matrix,
    host_to_client_affine_matrix,
)

print("host_to_client_affine_matrix")
print(host_to_client_affine_matrix)

url = browser.matrix_to_url(
    np.array(
        [
            client_matrix[0].T,
            (host_to_client_affine_matrix @ host_matrix[0]).T,
            # client_matrix[1].T,
            # (host_to_client_affine_matrix @ host_matrix[1]).T,
            # client_matrix[2].T,
            # (host_to_client_affine_matrix @ host_matrix[2]).T,
        ]
    )
)

# url = browser.matrix_to_url(
# np.array(
#         [
#             # host_matrix[0].T,
#             # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[0]).T,
#             # host_matrix[1].T,
#             # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[1]).T,
#             # host_matrix[2].T,
#             # (np.linalg.inv(host_to_client_affine_matrix) @ client_matrix[2]).T,
#         ]
#     )
# )

IFrame(src=url, width=1000, height=600)


host_to_client_affine_matrix
[[ 7.68471036e-01  1.24368716e-01  6.27681998e-01  1.40073682e-07]
 [-1.71652462e-01  9.85043703e-01  1.49778468e-02 -1.53006233e-07]
 [-6.16431424e-01 -1.19253201e-01  7.78325751e-01  3.16783120e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


# 出力

In [27]:
print("")

url = browser.matrix_to_url(
    np.array(
        [
            client_matrix[0].T,
            (host_to_client_affine_matrix @ host_matrix[0]).T,
            # client_matrix[1].T,
            # (host_to_client_affine_matrix @ host_matrix[1]).T,
            # client_matrix[2].T,
            # (host_to_client_affine_matrix @ host_matrix[2]).T,
        ]
    )
)
IFrame(src=url, width=1000, height=600)