In [3]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy.linalg import polar
from matplotlib import cm
import pandas as pd
import japanize_matplotlib

In [4]:
def decompose_affine_matrix(matrix: np.ndarray):
    """
    アフィン変換行列からスケーリング成分と回転行列を分離して抽出する。

    Parameters:
        matrix (np.ndarray): 4x4 アフィン変換行列

    Returns:
        scale: np.ndarray - x, y, z のスケーリング成分
        rotation: np.ndarray - 3x3 の回転行列
    """
    if matrix.shape != (4, 4):
        raise ValueError("Input matrix must be a 4x4 numpy array.")

    # 3x3 部分行列（回転 + スケーリング）
    M = matrix[:3, :3]

    # 極分解（M = R × S）
    R, S = polar(M)

    # スケーリング成分は S の対角要素の平方根（または M 各軸ベクトルのノルムでもOK）
    scale_x = np.linalg.norm(M[:, 0])
    scale_y = np.linalg.norm(M[:, 1])
    scale_z = np.linalg.norm(M[:, 2])
    scale = np.array([scale_x, scale_y, scale_z])

    return scale, R

In [6]:
transfomration_matrix = np.array([
 [-5.21985838e-01, -3.06889708e-01,  1.40137172e-02,  5.47509738e-09],
 [-1.01300482e-01,  8.40684739e-01, -2.22474867e-01, -1.22141997e-08],
 [ 6.23021862e-01, -2.05158764e-01, -1.62247263e-01,  7.86873677e-09],
 [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00]
])
scale, rotation = decompose_affine_matrix(transfomration_matrix)
print("スケーリング成分:", scale)
print("回転行列:\n", rotation)

スケーリング成分: [0.81907707 0.91816243 0.27570931]
回転行列:
 [[-0.72019446 -0.45235085 -0.52602153]
 [-0.14252408  0.83850039 -0.52593154]
 [ 0.67897484 -0.30380224 -0.66835422]]


In [ ]:
# スケーリング成分を除去
transfomration_matrix[:3, :3] = rotation