In [9]:
import numpy as np
import sqlite3

In [10]:
def generateAffineMatrix2D(points_A, points_B):
    # アフィン変換行列を求めるための最小二乗法
    ones = np.ones((points_A.shape[0], 1))
    P = np.hstack((points_A, ones))  # (N, 3)
    Q = points_B

    # 最小二乗法で解を求める
    affine_matrix, _, _, _ = np.linalg.lstsq(P, Q, rcond=None)  # (3, 2)

    # 3x3のアフィン変換行列を構築
    affine_matrix_3x3 = np.eye(3)
    affine_matrix_3x3[:2, :] = affine_matrix.T

    return affine_matrix_3x3

In [11]:
# ワールドから2つの座標系を作成
hash1 = "323"
hash2 = "525"
hash3 = "433"

In [ ]:
# データベースに接続
conn = sqlite3.connect("world.db")
c = conn.cursor()

# CREATE TABLE world (x INTEGER, y INTEGER, z INTEGER, hash TEXT, matrix_1_x REAL, matrix_1_y REAL, matrix_1_z REAL, matrix_2_x REAL, matrix_2_y REAL, matrix_2_z REAL)
# ワールドの座標系1のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash1,))
rows1 = c.fetchall()
rows1 = [list(row) for row in rows1 ]

# ワールドの座標系2のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash2,))
rows2 = c.fetchall()
rows2 = [list(row) for row in rows2]

# ワールドの座標系3のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash3,))
rows3 = c.fetchall()
rows3 = [list(row) for row in rows3]

c.close()

points_A = np.array([
    [rows1[0][4], rows1[0][5]],
    [rows2[0][4], rows2[0][5]],
    [rows3[0][4], rows3[0][5]]
])

points_B = np.array([
    [rows1[0][7], rows1[0][8]],
    [rows2[0][7], rows2[0][8]],
    [rows3[0][7], rows3[0][8]]
])

affine = generateAffineMatrix2D(points_A, points_B)
print(affine)

[[1.00000000e+00 3.69257393e-15 6.00000000e+00]
 [2.70714673e-15 1.00000000e+00 8.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
