In [1]:
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sqlite3
import os

In [2]:
# ワールドから2つの座標系を作成
# hash1 = "58145dd0e110aee0f8323bafe84bfdcf4f5568093503b0f7b9cf8dab822b9a12"
hash1 = "323"
# hash2 = "e8ecf3917e93f079f2b724871fee3aee314f445a0f824e038479f0e21b58c7e6"
hash2 = "525"
# hash3 = "ad86a80651f52dea498c34a2d3c766d327d8ed7a1d8900fac92b32ddfc859b8a"
hash3 = "433"

In [3]:
def generateAffineMatrix3D(matrix_affineA, matrix_affineAdash):
    # 各行列から平行移動を含む点を抽出
    points_A = np.array([mat[:3, 3] for mat in matrix_affineA])  # Aの各点 (x, y, z)
    points_Adash = np.array([mat[:3, 3] for mat in matrix_affineAdash])  # Adashの各点 (x', y', z')
    
    # アフィン変換行列を求めるための最小二乗法
    ones = np.ones((points_A.shape[0], 1))  # 点数分の1列
    P = np.hstack((points_A, ones))  # Aの点を拡張 [x, y, z, 1]
    print(P)
    Q = points_Adash  # Adashの点
    print(Q)
    
    # 最小二乗法で解を求める
    affine_matrix, _, _, _ = np.linalg.lstsq(P, Q, rcond=None)
    print("affine_matrix")
    print(affine_matrix)

    # 4x4のアフィン変換行列を構築
    affine_matrix_4x4 = np.eye(4)
    affine_matrix_4x4[:3, :] = affine_matrix.T
    
    return affine_matrix_4x4

def generateAffineMatrix3DSelf(matrix_affineA, matrix_affineAdash):
    # Aの点を拡張 [x, y, z, 1]
    points_A = np.array([mat[:3, 3] for mat in matrix_affineA])
    points_Adash = np.array([mat[:3, 3] for mat in matrix_affineAdash]) 
    
    # P = points_A
    P = np.hstack((points_A, np.ones((points_A.shape[0], 1))))
    # P = np.vstack((P, np.array([1, 1, 1, 1])))
    # print(P)
    Q = points_Adash
    # Q = np.hstack((points_Adash, np.ones((points_Adash.shape[0], 1))))
    # Q = np.vstack((Q, np.array([1, 1, 1, 1])))

    # print(Q)
    
    # 最小二乗法で解を求める
    affine_matrix = leastSquaresMethod(P, Q)
    
    # 4x4のアフィン変換行列を構築
    affine_matrix = np.vstack((affine_matrix.T, np.array([0, 0, 0, 1])))
    
    return affine_matrix

def generateAffineMatrix3DSelfLU(matrix_affineA, matrix_affineAdash):
    """LU分解を用いた最小二乗法でアフィン変換行列を求める"""
    points_A = np.array([mat[:3, 3] for mat in matrix_affineA])
    points_Adash = np.array([mat[:3, 3] for mat in matrix_affineAdash]) 
    
    # 拡張行列を作成
    P = np.hstack((points_A, np.ones((points_A.shape[0], 1))))
    # print(P)
    Q = points_Adash
    # print(Q)

    # 最小二乗法で解を求める
    affine_matrix = leastSquaresMethodLU(P, Q)

    print("affine_matrix")
    print(affine_matrix)

    # 4x4のアフィン変換行列を構築
    affine_matrix = np.vstack((affine_matrix.T, np.array([0, 0, 0, 1])))

    return affine_matrix

def LU(A: np.array) -> np.array:
    """LU分解"""
    n = A.shape[0]
    L = np.eye(n)
    U = np.zeros((n, n))
    for i in range(n):
        for j in range(i, n):
            U[i, j] = A[i, j] - np.sum(L[i, :i] * U[:i, j])
        # print("U")
        # print(U)
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - np.sum(L[j, :i] * U[:i, i])) / U[i, i]
        # print("L")
        # print(L)

    return L, U

def eq_solve(P: np.array, Q: np.array) -> np.array:
    # LU分解
    L, U = LU(P)
    print("L")
    print(L)
    print("U")
    print(U)
    n, m = Q.shape  # Q の形状を取得
    y = np.zeros((n, m))  # 前進代入の解ベクトル y を用意

    # 前進代入
    for i in range(n):
        # print("Q[i][k],dot",i)
        # print(Q[i, :],np.dot(L[i, :i], y[:i, :]))
        y[i, :] = Q[i, :] - np.dot(L[i, :i], y[:i, :])

    # print("y")
    # print(y)

    x = np.zeros((n, m))  # 解ベクトル x を用意

    # 後退代入
    for i in range(n - 1, -1, -1):
        if np.abs(U[i, i]) < 1e-8:  # 0除算防止
            print(f"Warning: U[{i}, {i}] is nearly zero. Adding small value.")
            U[i, i] = 1e-8
        print(f"np.dot({U[i, i+1:]}, {x[i+1:, :]})")
        print(y[i, :],"\n",np.dot(U[i, i+1:], x[i+1:, :]),"\n",U[i, i])
        x[i, :] = (y[i, :] - np.dot(U[i, i+1:], x[i+1:, :])) / U[i, i]
        # print(f"x {i}")
        # print(x)

    print("x")
    print(x)
    return x

def leastSquaresMethod(P: np.array, Q: np.array) -> np.array:
    # 最小二乗法と逆行列を用いた解法
    affine_matrix = np.linalg.inv(P.T @ P) @ P.T @ Q
    return affine_matrix

def leastSquaresMethodLU(P: np.array, Q: np.array) -> np.array:
    # 最小二乗法で解を求める
    affine_matrix = eq_solve(P.T @ P, P.T) @ Q
    print("eq_solve(P.T @ P, P.T)")
    print(eq_solve(P.T @ P, P.T))
    print("Q")
    print(Q)
    return affine_matrix

def leastSquaresMethod(P: np.array, Q: np.array) -> np.array:
    # 最小二乗法で解を求める
    affine_matrix = np.linalg.solve(P.T @ P, P.T) @ Q
    return affine_matrix

In [4]:
# データベースに接続
conn = sqlite3.connect("world.db")
c = conn.cursor()

# CREATE TABLE world (x INTEGER, y INTEGER, z INTEGER, hash TEXT, matrix_1_x REAL, matrix_1_y REAL, matrix_1_z REAL, matrix_2_x REAL, matrix_2_y REAL, matrix_2_z REAL)
# ワールドの座標系1のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash1,))
rows1 = c.fetchall()
rows1 = [list(row) for row in rows1 ]

# ワールドの座標系2のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash2,))
rows2 = c.fetchall()
rows2 = [list(row) for row in rows2]

# ワールドの座標系3のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash3,))
rows3 = c.fetchall()
rows3 = [list(row) for row in rows3]

c.close()

# ワールドの座標系1と座標系2のアフィン変換行列から座標系1と座標系3のアフィン変換行列を求める
matrix_affine1 = np.array([
    [[1, 0, 0, rows1[0][4]],[0, 1, 0, rows1[0][5]],[0, 0, 1, rows1[0][6]],[0, 0, 0, 1]],
    [[1, 0, 0, rows2[0][4]],[0, 1, 0, rows2[0][5]],[0, 0, 1, rows2[0][6]],[0, 0, 0, 1]],
    [[1, 0, 0, rows3[0][4]],[0, 1, 0, rows3[0][5]],[0, 0, 1, rows3[0][6]],[0, 0, 0, 1]],
])

print("matrix_affine1")
# print(matrix_affine1)

matrix_affine2 = np.array([
    [[1, 0, 0, rows1[0][7]],[0, 1, 0, rows1[0][8]],[0, 0, 1, rows1[0][9]],[0, 0, 0, 1]],
    [[1, 0, 0, rows2[0][7]],[0, 1, 0, rows2[0][8]],[0, 0, 1, rows2[0][9]],[0, 0, 0, 1]],
    [[1, 0, 0, rows3[0][7]],[0, 1, 0, rows3[0][8]],[0, 0, 1, rows3[0][9]],[0, 0, 0, 1]],
])

print("matrix_affine2")
print(matrix_affine2)

affine = generateAffineMatrix3D(matrix_affine1, matrix_affine2)
print(affine)
affine_self = generateAffineMatrix3DSelf(matrix_affine1, matrix_affine2)
print(affine_self)
affine_self_LU = generateAffineMatrix3DSelfLU(matrix_affine1, matrix_affine2)
print(affine_self_LU)

matrix_affine1
matrix_affine2
[[[ 1.  0.  0. 13.]
  [ 0.  1.  0. 15.]
  [ 0.  0.  1. 33.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0. 15.]
  [ 0.  1.  0. 15.]
  [ 0.  0.  1. 35.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0. 14.]
  [ 0.  1.  0. 16.]
  [ 0.  0.  1. 33.]
  [ 0.  0.  0.  1.]]]
[[ 7.  7. 23.  1.]
 [ 9.  7. 25.  1.]
 [ 8.  8. 23.  1.]]
[[13. 15. 33.]
 [15. 15. 35.]
 [14. 16. 33.]]
affine_matrix
[[ 0.7387218  -0.34398496 -0.43045113]
 [ 0.2612782   1.34398496  0.43045113]
 [ 0.2612782   0.34398496  1.43045113]
 [-0.0093985   0.08834586  0.09962406]]
[[ 0.7387218   0.2612782   0.2612782  -0.0093985 ]
 [-0.34398496  1.34398496  0.34398496  0.08834586]
 [-0.43045113  0.43045113  1.43045113  0.09962406]
 [ 0.          0.          0.          1.        ]]
[[ 1.48265235 -0.48265235 -0.48265235 17.10100398]
 [ 0.49176939  0.50823061 -0.49176939 19.31069596]
 [ 2.36543623 -2.36543623 -1.36543623 64.4050332 ]
 [ 0.          0.          0.          1.        ]]
L
[[1.         0.         0.         0.

In [5]:
# hash = "70163de61cd8d40eb0d70587c380b89c16e6620c2cd3862d5fc9a62bd6134e9c"
hash = "223"
# hash = "87cb9455225e82801c55d7f005a4fda7f7080f2a3bfa1f6ee9cb91e91a6d45ca"

In [6]:
conn = sqlite3.connect("world.db")
c = conn.cursor()

c.execute("SELECT * FROM world WHERE hash = ?", (hash,))
rows1 = c.fetchall()
rows1 = [list(row) for row in rows1 ]
print(rows1)

c.close()

matrix = np.array([
    rows1[0][4],
    rows1[0][5],
    rows1[0][6],
    1
])

print(matrix)
print(affine)

affine_times_matrix = np.dot(affine, matrix)

print(affine_times_matrix)
print(rows1[0][7],rows1[0][8],rows1[0][9])

[[2, 2, 3, '223', 6.0, 7.0, 23.0, 12.0, 15.0, 33.0]]
[ 6.  7. 23.  1.]
[[ 0.7387218   0.2612782   0.2612782  -0.0093985 ]
 [-0.34398496  1.34398496  0.34398496  0.08834586]
 [-0.43045113  0.43045113  1.43045113  0.09962406]
 [ 0.          0.          0.          1.        ]]
[12.2612782  15.34398496 33.43045113  1.        ]
12.0 15.0 33.0


In [7]:
conn = sqlite3.connect("world.db")
c = conn.cursor()

c.execute("SELECT * FROM world WHERE hash = ?", (hash,))
rows1 = c.fetchall()
rows1 = [list(row) for row in rows1 ]
print(rows1)

c.close()

matrix = np.array([
    rows1[0][4],
    rows1[0][5],
    rows1[0][6],
    1
])

print(matrix)
print(affine_self)

affine_self_times_matrix = np.dot(affine_self, matrix)

print(affine_self_times_matrix)
print(rows1[0][7],rows1[0][8],rows1[0][9])

[[2, 2, 3, '223', 6.0, 7.0, 23.0, 12.0, 15.0, 33.0]]
[ 6.  7. 23.  1.]
[[ 1.48265235 -0.48265235 -0.48265235 17.10100398]
 [ 0.49176939  0.50823061 -0.49176939 19.31069596]
 [ 2.36543623 -2.36543623 -1.36543623 64.4050332 ]
 [ 0.          0.          0.          1.        ]]
[11.51734765 14.50823061 30.63456377  1.        ]
12.0 15.0 33.0


In [8]:
conn = sqlite3.connect("world.db")
c = conn.cursor()

c.execute("SELECT * FROM world WHERE hash = ?", (hash,))
rows1 = c.fetchall()
rows1 = [list(row) for row in rows1 ]
print(rows1)

c.close()

matrix = np.array([
    rows1[0][4],
    rows1[0][5],
    rows1[0][6],
    1
])

print(matrix)
print(affine_self_LU)

affine_self_LU_times_matrix = np.dot(affine_self_LU, matrix)

print(affine_self_LU_times_matrix)
print(rows1[0][7],rows1[0][8],rows1[0][9])

[[2, 2, 3, '223', 6.0, 7.0, 23.0, 12.0, 15.0, 33.0]]
[ 6.  7. 23.  1.]
[[ 7.39130446e-01  2.60869554e-01  2.60869554e-01  2.66453526e-07]
 [-3.47826077e-01  1.34782608e+00  3.47826077e-01  2.22044605e-07]
 [-4.34782573e-01  4.34782573e-01  1.43478257e+00  8.21565038e-07]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[12.26086955 15.34782608 33.43478257  1.        ]
12.0 15.0 33.0


In [9]:
conn = sqlite3.connect("world.db")
c = conn.cursor()

c.execute("SELECT * FROM world WHERE hash = ?", (hash,))
rows1 = c.fetchall()
rows1 = [list(row) for row in rows1 ]
print(rows1)

c.close()

matrix = np.array([
    rows1[0][4],
    rows1[0][5],
    rows1[0][6],
    1
])

swiftFromAffineMatrix = np.array([[0.7391304328518187, 0.2608695671482568, 0.2608695671481893, -4.440892098500626e-08], [-0.34782609274896803, 1.3478260927490293, 0.3478260927489698, -1.3322676295501878e-07], [-0.4347826048339041, 0.4347826048341439, 1.434782604833929, 8.881784197001252e-08], [0.0, 0.0, 0.0, 1.0]])

print(matrix)
print(swiftFromAffineMatrix)

swiftFromAffineMatrix_times_matrix = np.dot(swiftFromAffineMatrix, matrix)

print(swiftFromAffineMatrix_times_matrix)
print(rows1[0][7],rows1[0][8],rows1[0][9])


[[2, 2, 3, '223', 6.0, 7.0, 23.0, 12.0, 15.0, 33.0]]
[ 6.  7. 23.  1.]
[[ 7.39130433e-01  2.60869567e-01  2.60869567e-01 -4.44089210e-08]
 [-3.47826093e-01  1.34782609e+00  3.47826093e-01 -1.33226763e-07]
 [-4.34782605e-01  4.34782605e-01  1.43478260e+00  8.88178420e-08]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[12.26086957 15.34782609 33.4347826   1.        ]
12.0 15.0 33.0


In [10]:
print(hash1, hash2, hash3)
print(hash)
# print(affine)
print(affine_times_matrix)
# print(affine_self)
print(affine_self_times_matrix)
# print(affine_self_LU)
print(affine_self_LU_times_matrix)
# print(swiftFromAffineMatrix)
print(swiftFromAffineMatrix_times_matrix)
print(rows1[0][7],rows1[0][8],rows1[0][9])

323 525 433
223
[12.2612782  15.34398496 33.43045113  1.        ]
[11.51734765 14.50823061 30.63456377  1.        ]
[12.26086955 15.34782608 33.43478257  1.        ]
[12.26086957 15.34782609 33.4347826   1.        ]
12.0 15.0 33.0


| |  	   1   |
|---|---|
|1 |	25.00000008 |
|2 |	23.99999987 |
|3 |	42.99999999 |
|4 |	1 |

---

|	|   1    |
|---|---|
|1|	24.99999982 |
|2|	24.00000002 |
|3|	42.99999995 |
|4|	1 |
 


In [11]:
for i in range(5 - 1, -1, -1):
    print(i)

4
3
2
1
0


In [12]:
A = np.array(
  [
    [
      [0.29195672273635864, 0.20753134787082672, -0.9336443543434143, 0.3406505584716797], [0.10483368486166, 0.9633494019508362, 0.24691641330718994, 1.0227067470550537], [0.950668454170227, -0.16996638476848602, 0.25950002670288086, -0.4758530557155609], [0.0, 0.0, 0.0, 0.9999997019767761]
    ],
    [
      [-0.03469759598374367, 0.003780881641432643, -0.9993905425071716, 0.4099700152873993], [-0.5030160546302795, 0.8640282154083252, 0.02073289453983307, 1.005720853805542], [0.8635802268981934, 0.5034287571907043, -0.028077878057956696, -0.37334659695625305], [0.0, 0.0, 0.0, 0.9999998211860657]
    ],
    [
      [0.8126243948936462, -0.1172361671924591, -0.5708739757537842, 0.25409597158432007], [-0.23279379308223724, -0.9633129239082336, -0.13354729115962982, 1.0099575519561768], [-0.5342738628387451, 0.2414197027683258, -0.8101032972335815, -0.4570466876029968], [0.0, 0.0, 0.0, 0.9999997615814209]
    ]
  ]
)

B = np.array(
  [
    [
      [0.45655980706214905, 0.7681077122688293, 0.44895800948143005, -0.26391538977622986], [-0.23043100535869598, -0.38531294465065, 0.8935520052909851, 0.9078537225723267], [0.8593336939811707, -0.5114138126373291, 0.0010774779366329312, -0.5531684756278992], [0.0, 0.0, 0.0, 1.0]
    ],
    [
      [0.011919788084924221, -0.8203105926513672, -0.5717933177947998, -0.35877254605293274], [0.4230100214481354, -0.5140084028244019, 0.7462285757064819, 0.9013289213180542], [-0.9060462713241577, -0.25076937675476074, 0.34087279438972473, -0.5011917948722839], [0.0, 0.0, 0.0, 0.9999998807907104]
    ],
    [
      [0.4490292966365814, 0.4107557237148285, -0.7935065627098083, -0.29981839656829834], [-0.8199097514152527, 0.5423877835273743, -0.18320521712303162, 0.9066635370254517], [0.35513556003570557, 0.7328680157661438, 0.5803306698799133, -0.6528453826904297], [0.0, 0.0, 0.0, 1.0000001192092896]
    ]
  ]
)

affine_test =  generateAffineMatrix3DSelfLU(A, B)
print(affine_test)

L
[[ 1.          0.          0.          0.        ]
 [ 2.91762783  1.          0.          0.        ]
 [-1.2369237  -0.59854277  1.          0.        ]
 [ 2.8814614   0.97949811  0.26299621  1.        ]]
U
[[ 3.48682979e-01  1.01732716e+00 -4.31294241e-01  1.00471655e+00]
 [ 0.00000000e+00  1.09235738e-01 -6.53822613e-02  1.06996199e-01]
 [ 0.00000000e+00  0.00000000e+00  2.10333736e-03  5.53169756e-04]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
np.dot([], [])
[-2.88657986e-15  1.77635684e-15  1.11022302e-15] 
 [0. 0. 0.] 
 1e-08
np.dot([0.00055317], [[-2.88657986e-07  1.77635684e-07  1.11022302e-07]])
[-0.03724718  0.01978107  0.01801927] 
 [-1.59676868e-10  9.82626880e-11  6.14141800e-11] 
 0.0021033373569123714
np.dot([-0.06538226  0.1069962 ], [[-1.77086084e+01  9.40461267e+00  8.56699195e+00]
 [-2.88657986e-07  1.77635684e-07  1.11022302e-07]])
[ 0.0288152  -0.19041907  0.26860007] 
 [ 1.15782883 -0.61489482 -0.56012929] 
 0.10923573830952504
np.dot([ 1

In [16]:
hash1 = "511"
hash2 = "225"
hash3 = "321"
hash4 = "103"


# データベースに接続
conn = sqlite3.connect("world.db")
c = conn.cursor()

# CREATE TABLE world (x INTEGER, y INTEGER, z INTEGER, hash TEXT, matrix_1_x REAL, matrix_1_y REAL, matrix_1_z REAL, matrix_2_x REAL, matrix_2_y REAL, matrix_2_z REAL)
# ワールドの座標系1のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash1,))
rows1 = c.fetchall()
rows1 = [list(row) for row in rows1 ]

# ワールドの座標系2のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash2,))
rows2 = c.fetchall()
rows2 = [list(row) for row in rows2]

# ワールドの座標系3のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash3,))
rows3 = c.fetchall()
rows3 = [list(row) for row in rows3]

# ワールドの座標系4のアフィン変換行列を取得
c.execute("SELECT * FROM world WHERE hash = ?", (hash4,))
rows4 = c.fetchall()
rows4 = [list(row) for row in rows4]

c.close()

# ワールドの座標系1と座標系2のアフィン変換行列から座標系1と座標系3のアフィン変換行列を求める
matrix_affine1 = np.array([
    [[1, 0, 0, rows1[0][4]],[0, 1, 0, rows1[0][5]],[0, 0, 1, rows1[0][6]],[0, 0, 0, 1]],
    [[1, 0, 0, rows2[0][4]],[0, 1, 0, rows2[0][5]],[0, 0, 1, rows2[0][6]],[0, 0, 0, 1]],
    [[1, 0, 0, rows3[0][4]],[0, 1, 0, rows3[0][5]],[0, 0, 1, rows3[0][6]],[0, 0, 0, 1]],
    [[1, 0, 0, rows4[0][4]],[0, 1, 0, rows4[0][5]],[0, 0, 1, rows4[0][6]],[0, 0, 0, 1]],
])

print("matrix_affine1")
print(matrix_affine1)

matrix_affine2 = np.array([
    [[1, 0, 0, rows1[0][7]],[0, 1, 0, rows1[0][8]],[0, 0, 1, rows1[0][9]],[0, 0, 0, 1]],
    [[1, 0, 0, rows2[0][7]],[0, 1, 0, rows2[0][8]],[0, 0, 1, rows2[0][9]],[0, 0, 0, 1]],
    [[1, 0, 0, rows3[0][7]],[0, 1, 0, rows3[0][8]],[0, 0, 1, rows3[0][9]],[0, 0, 0, 1]],
    [[1, 0, 0, rows4[0][7]],[0, 1, 0, rows4[0][8]],[0, 0, 1, rows4[0][9]],[0, 0, 0, 1]],
])

print("matrix_affine2")
print(matrix_affine2)

affine = generateAffineMatrix3D(matrix_affine1, matrix_affine2)
# print(affine)
affine_self = generateAffineMatrix3DSelf(matrix_affine1, matrix_affine2)
# print(affine_self)
affine_self_LU = generateAffineMatrix3DSelfLU(matrix_affine1, matrix_affine2)
print(affine_self_LU)

matrix_affine1
[[[ 1.  0.  0.  9.]
  [ 0.  1.  0.  6.]
  [ 0.  0.  1. 21.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0.  6.]
  [ 0.  1.  0.  7.]
  [ 0.  0.  1. 25.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0.  7.]
  [ 0.  1.  0.  7.]
  [ 0.  0.  1. 21.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0.  5.]
  [ 0.  1.  0.  5.]
  [ 0.  0.  1. 23.]
  [ 0.  0.  0.  1.]]]
matrix_affine2
[[[ 1.  0.  0. 15.]
  [ 0.  1.  0. 14.]
  [ 0.  0.  1. 31.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0. 12.]
  [ 0.  1.  0. 15.]
  [ 0.  0.  1. 35.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0. 13.]
  [ 0.  1.  0. 15.]
  [ 0.  0.  1. 31.]
  [ 0.  0.  0.  1.]]

 [[ 1.  0.  0. 11.]
  [ 0.  1.  0. 13.]
  [ 0.  0.  1. 33.]
  [ 0.  0.  0.  1.]]]
[[ 9.  6. 21.  1.]
 [ 6.  7. 25.  1.]
 [ 7.  7. 21.  1.]
 [ 5.  5. 23.  1.]]
[[15. 14. 31.]
 [12. 15. 35.]
 [13. 15. 31.]
 [11. 13. 33.]]
affine_matrix
[[ 1.00000000e+00  1.37442484e-16  3.84838954e-15]
 [-3.18039205e-15  1.00000000e+00 -4.38807654e-15]
 [ 1.11098864e-15  8.36090241e-16  1.00000000e+00]
 [ 6.0000