In [2]:
import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import sqlite3
import os

In [3]:
pyL = np.array(
    [
        [ 1.        ,  0.         , 0.        ,  0.        ],
        [ 2.91762783,  1.         , 0.        ,  0.        ],
        [-1.2369237 , -0.59854277 , 1.        ,  0.        ],
        [ 2.8814614 ,  0.97949811 , 0.26299621,  1.        ]
    ]
)
pyU = np.array(
    [
        [ 3.48682979e-01 , 1.01732716e+00 ,-4.31294241e-01 , 1.00471655e+00],
        [ 0.00000000e+00 , 1.09235738e-01 ,-6.53822613e-02 , 1.06996199e-01],
        [ 0.00000000e+00 , 0.00000000e+00 , 2.10333736e-03 , 5.53169756e-04],
        [ 0.00000000e+00 , 0.00000000e+00 , 0.00000000e+00 , 0.00000000e+00]
    ]
)

swiftL = np.array(
    [
[1.0, 0.0, 0.0, 0.0],
[2.9176278294744384, 1.0, 0.0, 0.0],
[-1.2369237018121708, -0.5985427693547177, 1.0, 0.0],
[2.881461399855663, 0.979498111563778, 0.26299621145309915, 1.0]
    ]
)
swiftU = np.array(
[
[0.34868297919719726, 1.0173271637697994, -0.4312942413874934, 1.004716545343399],
[0.0, 0.10923573830952504, -0.06538226132029012, 0.10699619938945482],
[0.0, 0.0, 0.0021033373569123714, 0.0005531697562759508],
[0.0, 0.0, 0.0, 0.0]
]
)

diffU = swiftU - pyU
diffL = swiftL - pyL

print("diffU")
print(diffU)
print("diffL")
print(diffL)

diffU
[[ 1.97197259e-10  3.76979936e-09 -3.87493371e-10 -4.65660088e-09]
 [ 0.00000000e+00  3.09525044e-10 -2.02901307e-11  3.89454816e-10]
 [ 0.00000000e+00  0.00000000e+00 -3.08762868e-12  2.75950812e-13]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
diffL
[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.25561372e-10  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.81217086e-09  6.45282272e-10  0.00000000e+00  0.00000000e+00]
 [-1.44336987e-10  1.56377800e-09  1.45309914e-09  0.00000000e+00]]


In [4]:
pyY = np.array(
[[ 3.40650558e-01,  4.09970015e-01 , 2.54095972e-01, 0.],
 [ 2.88151975e-02, -1.90419072e-01 , 2.68600074e-01, 0.],
 [-3.72471778e-02,  1.97810733e-02 , 1.80192743e-02, 0.],
 [-2.88657986e-15,  1.77635684e-15 , 1.11022302e-15, 0.]]
)

swiftY = np.array(
    [
        [0.3406505584716797, 0.4099700152873993, 0.25409597158432007, 0.0],
        [0.028815197532071624, -0.19041907204703512, 0.2686000739044184, 0.0],
        [-0.03724717777603814, 0.019781073264041216, 0.01801927426827299, 0.0],
        [-2.886579864025407e-15, 1.6653345369377348e-15, 1.2212453270876722e-15, 0.0]
    ]
)

diffY = swiftY - pyY

print("diffY")
print(diffY)

diffY
[[ 4.71679695e-10  2.87399271e-10 -4.15679935e-10  0.00000000e+00]
 [ 3.20716231e-11 -4.70351258e-11 -9.55815982e-11  0.00000000e+00]
 [ 2.39618603e-11 -3.59587846e-11 -3.17270099e-11  0.00000000e+00]
 [-4.02540692e-24 -1.11022303e-16  1.11022307e-16  0.00000000e+00]]


In [5]:
nyanPy = np.array(
[-2.88657986e-15,  1.77635684e-15,  1.11022302e-15] 
)

naynSwift = np.array(
    [
    -2.886579864025407e-07,
    1.6653345369377348e-07,
    1.2212453270876722e-07,
    ]
)

diffN = naynSwift - nyanPy
print("diffN")
print(diffN)



diffN
[-2.88657984e-07  1.66533452e-07  1.22124532e-07]
